name: Autograder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  grading:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]' && github.actor != 'ArthurCRodrigues' 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
           path: submission

      - name: Check repository criteria
        uses: webtech-network/autograder@web-01-1
        with: 
          redis_name: ${{ secrets.REDIS_NAME }}
          redis_url: ${{ secrets.REDIS_URL }}
          autograder_engine: ${{ secrets.ENGINE }}
